import type { Item, Collection, Tag } from "@/types";

export const MOCK_TAGS: Tag[] = [
  { id: "t1", userId: "u1", name: "Machine Learning", color: "#6B8E8E", isAiGenerated: true, createdAt: "2026-03-01T00:00:00Z" },
  { id: "t2", userId: "u1", name: "Web Development", color: "#8B7E6A", isAiGenerated: false, createdAt: "2026-03-02T00:00:00Z" },
  { id: "t3", userId: "u1", name: "Design Systems", color: "#7A8B6E", isAiGenerated: true, createdAt: "2026-03-03T00:00:00Z" },
  { id: "t4", userId: "u1", name: "TypeScript", color: "#6E7A8B", isAiGenerated: false, createdAt: "2026-03-04T00:00:00Z" },
  { id: "t5", userId: "u1", name: "Productivity", color: "#8B6E7A", isAiGenerated: true, createdAt: "2026-03-05T00:00:00Z" },
  { id: "t6", userId: "u1", name: "Research", color: "#7A6E8B", isAiGenerated: false, createdAt: "2026-03-06T00:00:00Z" },
];

export const MOCK_ITEMS: Item[] = [
  {
    id: "1",
    userId: "u1",
    url: "https://blog.openai.com/new-reasoning-models",
    title: "OpenAI's New Reasoning Models: A Deep Dive",
    description: "An in-depth look at how OpenAI's latest models achieve better reasoning through chain-of-thought prompting and reinforcement learning from human feedback.",
    contentText: null,
    thumbnailUrl: null,
    fileUrl: null,
    itemType: "article",
    saveSource: "web_url",
    status: "ready",
    readingTime: 12,
    wordCount: 3200,
    sourceDomain: "blog.openai.com",
    author: "OpenAI Research",
    publishedAt: "2026-03-15T10:00:00Z",
    savedAt: "2026-03-20T14:30:00Z",
    lastViewedAt: "2026-03-25T09:00:00Z",
    viewCount: 5,
    isArchived: false,
    isFavourite: true,
    userNote: "Great overview of reasoning improvements",
    youtubeTimestamp: null,
    tags: [
      { tagId: "t1", tagName: "Machine Learning", tagColor: "#6B8E8E", isAiGenerated: true, confidence: 0.95 },
      { tagId: "t6", tagName: "Research", tagColor: "#7A6E8B", isAiGenerated: false, confidence: 1.0 },
    ],
  },
  {
    id: "2",
    userId: "u1",
    url: "https://www.youtube.com/watch?v=abc123",
    title: "Building a Design System from Scratch — Figma to Code",
    description: "A practical walkthrough of creating a complete design system, from Figma tokens to coded React components.",
    contentText: null,
    thumbnailUrl: null,
    fileUrl: null,
    itemType: "youtube",
    saveSource: "extension",
    status: "ready",
    readingTime: null,
    wordCount: null,
    sourceDomain: "youtube.com",
    author: "DesignCourse",
    publishedAt: "2026-03-18T08:00:00Z",
    savedAt: "2026-03-22T11:00:00Z",
    lastViewedAt: null,
    viewCount: 0,
    isArchived: false,
    isFavourite: false,
    userNote: null,
    youtubeTimestamp: 125,
    tags: [
      { tagId: "t3", tagName: "Design Systems", tagColor: "#7A8B6E", isAiGenerated: true, confidence: 0.88 },
      { tagId: "t2", tagName: "Web Development", tagColor: "#8B7E6A", isAiGenerated: false, confidence: 1.0 },
    ],
  },
  {
    id: "3",
    userId: "u1",
    url: "https://twitter.com/dan_abramov/status/123456",
    title: "Dan Abramov on React Server Components",
    description: "Thread explaining why RSC changes the game for data fetching and code splitting in React applications.",
    contentText: null,
    thumbnailUrl: null,
    fileUrl: null,
    itemType: "tweet",
    saveSource: "web_url",
    status: "ready",
    readingTime: 2,
    wordCount: 840,
    sourceDomain: "twitter.com",
    author: "Dan Abramov",
    publishedAt: "2026-03-25T16:00:00Z",
    savedAt: "2026-03-26T08:15:00Z",
    lastViewedAt: "2026-03-27T10:00:00Z",
    viewCount: 3,
    isArchived: false,
    isFavourite: true,
    userNote: "Important for the RSC migration project",
    youtubeTimestamp: null,
    tags: [
      { tagId: "t2", tagName: "Web Development", tagColor: "#8B7E6A", isAiGenerated: false, confidence: 1.0 },
      { tagId: "t4", tagName: "TypeScript", tagColor: "#6E7A8B", isAiGenerated: true, confidence: 0.72 },
    ],
  },
  {
    id: "4",
    userId: "u1",
    url: null,
    title: "Q1 2026 Research Report — AI Trends",
    description: "Quarterly analysis of emerging AI trends, market movements, and technology shifts.",
    contentText: null,
    thumbnailUrl: null,
    fileUrl: "https://r2.example.com/uploads/u1/4/report.pdf",
    itemType: "pdf",
    saveSource: "web_upload",
    status: "ready",
    readingTime: 35,
    wordCount: 8500,
    sourceDomain: null,
    author: null,
    publishedAt: null,
    savedAt: "2026-03-28T09:00:00Z",
    lastViewedAt: null,
    viewCount: 0,
    isArchived: false,
    isFavourite: false,
    userNote: "Downloaded from internal wiki",
    youtubeTimestamp: null,
    tags: [
      { tagId: "t1", tagName: "Machine Learning", tagColor: "#6B8E8E", isAiGenerated: true, confidence: 0.91 },
      { tagId: "t5", tagName: "Productivity", tagColor: "#8B6E7A", isAiGenerated: true, confidence: 0.65 },
    ],
  },
  {
    id: "5",
    userId: "u1",
    url: "https://overreacted.io/things-i-dont-wanna-know",
    title: "Things I Don't Wanna Know as a Developer",
    description: "A thoughtful essay on the cognitive burden of knowing too many tools and frameworks.",
    contentText: null,
    thumbnailUrl: null,
    fileUrl: null,
    itemType: "article",
    saveSource: "extension",
    status: "processing",
    readingTime: null,
    wordCount: null,
    sourceDomain: "overreacted.io",
    author: "Dan Abramov",
    publishedAt: "2026-03-29T12:00:00Z",
    savedAt: "2026-03-30T17:45:00Z",
    lastViewedAt: null,
    viewCount: 0,
    isArchived: false,
    isFavourite: false,
    userNote: null,
    youtubeTimestamp: null,
    tags: [],
  },
  {
    id: "6",
    userId: "u1",
    url: "https://podcasts.apple.com/episode/syntax-fm-800",
    title: "Syntax FM #800 — The Future of Full-Stack TypeScript",
    description: "Wes Bos and Scott Tolinski discuss server actions, edge functions, and the convergence of frontend and backend.",
    contentText: null,
    thumbnailUrl: null,
    fileUrl: null,
    itemType: "podcast",
    saveSource: "web_url",
    status: "ready",
    readingTime: null,
    wordCount: null,
    sourceDomain: "podcasts.apple.com",
    author: "Syntax FM",
    publishedAt: "2026-03-20T06:00:00Z",
    savedAt: "2026-03-21T10:30:00Z",
    lastViewedAt: "2026-03-22T08:00:00Z",
    viewCount: 2,
    isArchived: false,
    isFavourite: false,
    userNote: null,
    youtubeTimestamp: null,
    tags: [
      { tagId: "t4", tagName: "TypeScript", tagColor: "#6E7A8B", isAiGenerated: true, confidence: 0.93 },
      { tagId: "t2", tagName: "Web Development", tagColor: "#8B7E6A", isAiGenerated: true, confidence: 0.87 },
    ],
  },
];

export const MOCK_COLLECTIONS: Collection[] = [
  { id: "c1", userId: "u1", name: "AI Research", description: "Papers and articles about AI/ML", coverImage: null, isPublic: false, publicSlug: null, itemCount: 8, createdAt: "2026-03-01T00:00:00Z" },
  { id: "c2", userId: "u1", name: "Frontend Inspo", description: "UI design ideas and component patterns", coverImage: null, isPublic: true, publicSlug: "frontend-inspo", itemCount: 14, createdAt: "2026-03-05T00:00:00Z" },
  { id: "c3", userId: "u1", name: "Career Development", description: "Articles about career growth", coverImage: null, isPublic: false, publicSlug: null, itemCount: 5, createdAt: "2026-03-10T00:00:00Z" },
];
