"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useTags, useCreateTag, useUpdateTag, useDeleteTag } from "@/hooks/useTags";
import { getApiErrorMessage } from "@/lib/api";
import { EmptyState } from "@/components/shared/EmptyState";
import { LoaderFive } from "@/components/ui/unique-loader-components";

export default function TagsPage() {
  const router = useRouter();
  const { data: tags, isLoading, error } = useTags();
  const createTag = useCreateTag();
  const updateTag = useUpdateTag();
  const deleteTag = useDeleteTag();
  const [newName, setNewName] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editingName, setEditingName] = useState("");
  const [actionError, setActionError] = useState<string | null>(null);

  const handleCreate = async () => {
    const name = newName.trim();
    if (!name) return setActionError("Tag name is required.");
    if (tags?.some((tag) => tag.name.trim().toLowerCase() === name.toLowerCase())) {
      return setActionError("A tag with that name already exists.");
    }
    try {
      setActionError(null);
      await createTag.mutateAsync({ name });
      setNewName("");
    } catch (err) {
      setActionError(getApiErrorMessage(err, "Tag could not be created."));
    }
  };

  const handleUpdate = async (id: string) => {
    const name = editingName.trim();
    if (!name) return setActionError("Tag name is required.");
    if (tags?.some((tag) => tag.id !== id && tag.name.trim().toLowerCase() === name.toLowerCase())) {
      return setActionError("A tag with that name already exists.");
    }
    try {
      setActionError(null);
      await updateTag.mutateAsync({ id, name });
      setEditingId(null);
    } catch (err) {
      setActionError(getApiErrorMessage(err, "Tag could not be renamed."));
    }
  };

  const handleDelete = async (id: string) => {
    try {
      setActionError(null);
      await deleteTag.mutateAsync(id);
    } catch (err) {
      setActionError(getApiErrorMessage(err, "Tag could not be deleted."));
    }
  };

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold" style={{ color: "var(--text-primary)" }}>
          Tags
        </h1>
        <p className="text-sm mt-1" style={{ color: "var(--text-tertiary)" }}>
          {tags?.length || 0} tags in your library
        </p>
      </div>

      <div className="mb-6 flex flex-wrap gap-2">
        <input
          aria-label="New tag name"
          value={newName}
          onChange={(event) => setNewName(event.target.value)}
          onKeyDown={(event) => { if (event.key === "Enter") void handleCreate(); }}
          placeholder="Create a tag"
          className="min-w-56 flex-1 rounded-lg border px-3 py-2 text-sm outline-none"
          style={{ background: "var(--bg-secondary)", borderColor: "var(--border)", color: "var(--text-primary)" }}
        />
        <button
          type="button"
          onClick={() => void handleCreate()}
          disabled={createTag.isPending}
          className="rounded-lg px-4 py-2 text-sm font-medium disabled:opacity-60"
          style={{ background: "var(--accent-500)", color: "white" }}
        >
          {createTag.isPending ? "Creating..." : "Create tag"}
        </button>
      </div>
      {actionError && <p role="alert" className="mb-5 text-sm text-red-400">{actionError}</p>}

      {error ? (
        <div
          className="p-8 text-center rounded-lg border"
          style={{
            color: "color-mix(in srgb, #ef4444 70%, var(--text-primary) 30%)",
            background: "color-mix(in srgb, var(--bg-secondary) 88%, #b91c1c 12%)",
            borderColor: "color-mix(in srgb, var(--border) 50%, #dc2626 50%)",
          }}
        >
          Failed to load tags.
        </div>
      ) : isLoading ? (
        <div className="flex flex-col items-center justify-center py-20 w-full">
          <LoaderFive text="Analyzing your tags" />
        </div>
      ) : tags?.length === 0 ? (
        <EmptyState
          icon="🏷️"
          title="No tags yet"
          description="Tags are automatically generated by AI when you save items, but you can also add them manually."
        />
      ) : (
        <div className="flex flex-wrap gap-3">
          {tags?.map((tag) => (
            <div
              key={tag.id}
              className="flex items-center gap-2 px-4 py-2.5 rounded-xl card-hover"
              style={{
                background: "var(--bg-secondary)",
                boxShadow: "var(--shadow-card)",
                borderRadius: "var(--radius-lg)",
              }}
            >
              <button
                type="button"
                aria-label={`Search for ${tag.name}`}
                onClick={() => router.push(`/dashboard/search?q=${encodeURIComponent(tag.name)}&type=keyword`)}
                className="flex items-center gap-2"
              >
              <span
                className="w-3 h-3 rounded-full"
                style={{ background: tag.color ?? "var(--text-tertiary)" }}
              />
              <span className="text-sm font-medium" style={{ color: "var(--text-primary)" }}>
                {tag.name}
              </span>
              <span className="text-xs ml-1" style={{ color: "var(--text-tertiary)" }}>
                {tag._count?.items || 0}
              </span>
              </button>
              {editingId === tag.id ? (
                <>
                  <input
                    aria-label={`Rename ${tag.name}`}
                    value={editingName}
                    onChange={(event) => setEditingName(event.target.value)}
                    className="w-28 rounded border px-2 py-1 text-xs"
                  />
                  <button type="button" onClick={() => void handleUpdate(tag.id)} className="text-xs underline">Save</button>
                  <button type="button" onClick={() => setEditingId(null)} className="text-xs underline">Cancel</button>
                </>
              ) : (
                <>
                  <button type="button" aria-label={`Rename ${tag.name}`} onClick={() => { setEditingId(tag.id); setEditingName(tag.name); }} className="text-xs underline">Edit</button>
                  <button type="button" aria-label={`Delete ${tag.name}`} onClick={() => void handleDelete(tag.id)} className="text-xs text-red-400 underline">Delete</button>
                </>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
