"use client";

import { useTags } from "@/hooks/useTags";
import { EmptyState } from "@/components/shared/EmptyState";

export default function TagsPage() {
  const { data: tags, isLoading, error } = useTags();

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold" style={{ color: "var(--text-primary)" }}>
          Tags
        </h1>
        <p className="text-sm mt-1" style={{ color: "var(--text-tertiary)" }}>
          {tags?.length || 0} tags in your library
        </p>
      </div>

      {error ? (
        <div className="p-8 text-center text-red-500 bg-red-50 rounded-lg">
          Failed to load tags.
        </div>
      ) : isLoading ? (
        <div className="flex flex-wrap gap-3">
          {Array.from({ length: 12 }).map((_, i) => (
            <div key={i} className="w-24 h-10 border border-slate-100 rounded-xl bg-slate-50 animate-pulse" />
          ))}
        </div>
      ) : tags?.length === 0 ? (
        <EmptyState
          icon="🏷️"
          title="No tags yet"
          description="Tags are automatically generated by AI when you save items, but you can also add them manually."
        />
      ) : (
        <div className="flex flex-wrap gap-3">
          {tags?.map((tag) => (
            <div
              key={tag.id}
              className="flex items-center gap-2 px-4 py-2.5 rounded-xl cursor-pointer card-hover"
              style={{
                background: "var(--bg-secondary)",
                boxShadow: "var(--shadow-card)",
                borderRadius: "var(--radius-lg)",
              }}
            >
              <span
                className="w-3 h-3 rounded-full"
                style={{ background: tag.color ?? "var(--text-tertiary)" }}
              />
              <span className="text-sm font-medium" style={{ color: "var(--text-primary)" }}>
                {tag.name}
              </span>
              <span className="text-xs ml-1" style={{ color: "var(--text-tertiary)" }}>
                {tag._count?.items || 0}
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
