export const authClerkAppearance = {
  variables: {
    colorScheme: "dark",
    colorPrimary: "#ffffff",
    colorText: "#f4f4f5",
    colorTextSecondary: "#a1a1aa",
    colorInputText: "#f4f4f5",
    colorInputBackground: "#09090b",
    colorTextOnPrimaryBackground: "#000000",
    colorBackground: "transparent",
    colorDanger: "#ef4444",
    colorSuccess: "#10b981",
    colorWarning: "#f59e0b",
    borderRadius: "0.75rem",
    fontFamily: "Inter, system-ui, sans-serif",
  },
  elements: {
    rootBox: "w-full ",
    cardBox: "w-full",
    card: "w-full rounded-3xl border border-white/10 bg-black/60 backdrop-blur-3xl shadow-[0_32px_64px_-16px_rgba(0,0,0,0.8)] px-6 py-7 sm:px-8 sm:py-8",
    headerTitle: "text-zinc-100 text-2xl font-bold tracking-tight mb-1 text-left",
    headerSubtitle: "text-zinc-400 text-[13px] leading-relaxed mb-3 text-left",
    socialButtonsBlock: "flex flex-col sm:flex-row gap-2.5 mb-3.5",
    socialButtonsBlockButton:
      "h-12 border border-white/10 bg-white/5 text-zinc-100 hover:bg-white/10 transition-all duration-300 rounded-xl",
    socialButtonsBlockButtonText: "text-zinc-100 font-semibold text-sm",
    socialButtonsBlockButtonArrow: "text-zinc-400",
    socialButtonsProviderIcon__github: "invert brightness-100 w-4 h-4",
    socialButtonsProviderIcon__google: "brightness-110 w-4 h-4",
    dividerLine: "bg-white/10 h-[1px]",
    dividerText: "text-zinc-500 text-[10px] font-bold uppercase tracking-[0.3em] px-3",
    formField: "mb-2.5",
    formFieldLabel: "text-zinc-400 text-[9px] font-bold uppercase tracking-[0.15em] mb-1 block opacity-60",
    formFieldInput:
      "h-12 rounded-xl border border-white/10 bg-white/5 text-zinc-100 placeholder:text-zinc-600 transition-all duration-300 focus:border-white/30 focus:bg-white/10 focus:ring-4 focus:ring-white/5 px-4 text-sm",
    formFieldInputShowPasswordButton: "text-zinc-500 hover:text-zinc-100 mr-2 scale-90",
    formFieldErrorText: "text-red-400 text-[11px] mt-1 font-medium ml-1",
    alertText: "text-red-400 font-medium",
    otpCodeFieldInput:
      "h-12 rounded-xl border border-white/10 bg-white/5 text-zinc-100 focus:border-white/30 focus:ring-4 focus:ring-white/5",
    formButtonPrimary:
      "h-12 w-full rounded-xl bg-zinc-100 text-zinc-950 font-bold shadow-[0_20px_40px_-15px_rgba(255,255,255,0.2)] hover:bg-white hover:scale-[1.01] active:scale-[0.98] transition-all duration-400 text-xs tracking-[0.2em] uppercase mt-2 mb-1",
    footer: "mt-3 border-t border-white/5 pt-4",
    footerActionText: "text-zinc-500 text-sm",
    footerActionLink: "text-zinc-100 font-bold hover:text-white transition-colors ml-1",
    formResendCodeLink: "text-zinc-100 hover:text-zinc-300 transition-colors",
    identityPreviewText: "text-zinc-100 font-medium",
    identityPreviewEditButton: "text-zinc-100 hover:text-white transition-colors",
    formFieldSuccessText: "text-emerald-400 text-xs mt-1.5 ml-1",
    formFieldWarningText: "text-amber-400 text-xs mt-1.5 ml-1",
    alert: "bg-red-500/10 border border-red-500/20 rounded-2xl p-4",
  },
};


